RAILS_ENV = ENV['RAILS_ENV'] || `cat .rails-env 2>/dev/null`.to_s.split.first || 'development'

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'
gem 'andpush'
gem 'attr_encrypted'
gem 'audited'
gem 'aws-sdk-s3'
gem 'bcrypt'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'browser'
gem 'csv'
gem 'discordrb-webhooks'
gem 'factory_bot_rails'
gem 'faker'
gem 'faraday'
gem 'forgery'
gem 'graphql'
gem 'hiredis'
gem 'irb'
gem 'jbuilder'
gem 'kaminari'
gem 'lockbox'
gem 'mini_magick'
gem 'pg', '~> 1.0'
gem 'phonelib'
gem 'puma'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '6.0.0'
gem 'rails-i18n'
gem 'redis'
gem 'request_store_rails'
gem 'roo', '~> 2.8.0'
gem 'scenic'
gem 'sidekiq'
gem 'slack-notifier'
gem 'tzinfo-data'
gem 'whenever'

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-safe-deploy-to'
  gem 'capistrano-slackify'
  gem 'capistrano3-puma'
  gem 'lefthook'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'brakeman'
  gem 'bundle-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'derailed_benchmarks'
  gem 'memory_profiler'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-gitlab-security'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end
